# Generated by Django 3.0.8 on 2020-07-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_chat', '0003_auto_20200715_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=models.SET('none'), to='service_chat.Author'),
        ),
    ]
